{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    vim
    neovim
    logitech-udev-rules
    solaar
    gnomeExtensions.dash-to-dock
    gnomeExtensions.blur-my-shell
    gnomeExtensions.hibernate-status-button
    gnome-tweaks
    open-vm-tools
    albert
    gjs
    wofi
    rofi
    waybar
    blueberry
    networkmanagerapplet
    brightnessctl
    hyprlock
    firefox
    wireguard-tools
  ];
  environment.gnome.excludePackages = with pkgs; [
    epiphany
    gedit
    totem
    yelp
    geary
    gnome-calendar
    gnome-contacts
    gnome-console
    gnome-maps
    gnome-music
    gnome-text-editor
    pkgs.gnome-photos
    pkgs.gnome-tour
    evince
    xterm
  ];
}
