{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    vim
    neovim
    logitech-udev-rules
    solaar
    gnomeExtensions.dash-to-dock
    gnomeExtensions.hide-top-bar
    gnomeExtensions.gtile
    gnomeExtensions.blur-my-shell
    gnomeExtensions.hibernate-status-button
    gnomeExtensions.gtile
    gnomeExtensions.rounded-corners
    gnome-tweaks
    open-vm-tools
    gjs
    blueberry
    networkmanagerapplet
    brightnessctl
    firefox
    wireguard-tools
    nextcloud-client
    ulauncher
    bitwarden-desktop
    pythonManylinuxPackages.manylinux2014Package
  ];
  environment.gnome.excludePackages = with pkgs; [
    epiphany
    gedit
    totem
    yelp
    geary
    gnome-contacts
    gnome-console
    gnome-maps
    gnome-music
    gnome-text-editor
    pkgs.gnome-photos
    pkgs.gnome-tour
    evince
    xterm
  ];
}
